### This function holds a vector of BCI species names as originally
### defined in the first release and prints the matrix of changed
### names since then.
`BCI.nomina` <-
    function()
{

    oldnames <- c("Abarema.macradenium", "Acacia.melanoceras",
"Acalypha.diversifolia", "Acalypha.macrostachya", "Adelia.triloba",
"Aegiphila.panamensis", "Alchornea.costaricensis",
"Alchornea.latifolia", "Alibertia.edulis", "Allophylus.psilospermus",
"Alseis.blackiana", "Amaioua.corymbosa", "Anacardium.excelsum",
"Andira.inermis", "Annona.spraguei", "Apeiba.aspera",
"Apeiba.tibourbou", "Aspidosperma.cruenta",
"Astrocaryum.standleyanum", "Astronium.graveolens",
"Attalea.butyracea", "Banara.guianensis", "Beilschmiedia.pendula",
"Brosimum.alicastrum", "Brosimum.guianense",
"Calophyllum.longifolium", "Casearia.aculeata", "Casearia.arborea",
"Casearia.commersoniana", "Casearia.guianensis",
"Casearia.sylvestris", "Cassipourea.elliptica",
"Cavanillesia.platanifolia", "Cecropia.insignis",
"Cecropia.obtusifolia", "Cedrela.odorata", "Ceiba.pentandra",
"Celtis.schippii", "Cespedezia.macrophylla", "Chamguava.schippii",
"Chimarrhis.parviflora", "Chlorophora.tinctoria",
"Chrysochlamys.eclipes", "Chrysophyllum.argenteum",
"Chrysophyllum.cainito", "Coccoloba.coronata",
"Coccoloba.manzanillensis", "Colubrina.glandulosa",
"Cordia.alliodora", "Cordia.bicolor", "Cordia.lasiocalyx",
"Coussarea.curvigemmia", "Croton.billbergianus", "Cupania.cinerea",
"Cupania.latifolia", "Cupania.rufescens", "Cupania.sylvatica",
"Dendropanax.arboreus", "Desmopsis.panamensis",
"Diospyros.artanthifolia", "Dipteryx.panamensis",
"Drypetes.standleyi", "Elaeis.oleifera", "Enterolobium.schomburgkii",
"Erythrina.costaricensis", "Erythroxylum.macrophyllum",
"Eugenia.coloradensis", "Eugenia.galalonensis", "Eugenia.nesiotica",
"Eugenia.oerstedeana", "Faramea.occidentalis", "Ficus.colubrinae",
"Ficus.costaricana", "Ficus.insipida", "Ficus.maxima",
"Ficus.obtusifolia", "Ficus.popenoei", "Ficus.tonduzii",
"Ficus.trigonata", "Ficus.yoponensis", "Garcinia.intermedia",
"Garcinia.madruno", "Genipa.americana", "Guapira.standleyana",
"Guarea.fuzzy", "Guarea.grandifolia", "Guarea.guidonia",
"Guatteria.dumetorum", "Guazuma.ulmifolia", "Guettarda.foliacea",
"Gustavia.superba", "Hampea.appendiculata", "Hasseltia.floribunda",
"Heisteria.acuminata", "Heisteria.concinna", "Hirtella.americana",
"Hirtella.triandra", "Hura.crepitans", "Hyeronima.alchorneoides",
"Inga.acuminata", "Inga.cocleensis", "Inga.goldmanii", "Inga.laurina",
"Inga.marginata", "Inga.nobilis", "Inga.oerstediana",
"Inga.pezizifera", "Inga.punctata", "Inga.ruiziana",
"Inga.sapindoides", "Inga.spectabilis", "Inga.umbellifera",
"Jacaranda.copaia", "Lacistema.aggregatum", "Lacmellea.panamensis",
"Laetia.procera", "Laetia.thamnia", "Lafoensia.punicifolia",
"Licania.hypoleuca", "Licania.platypus", "Lindackeria.laurina",
"Lonchocarpus.latifolius", "Luehea.seemannii", "Macrocnemum.roseum",
"Maquira.costaricana", "Margaritaria.nobilis", "Marila.laxiflora",
"Maytenus.schippii", "Miconia.affinis", "Miconia.argentea",
"Miconia.elata", "Miconia.hondurensis", "Mosannona.garwoodii",
"Myrcia.gatunensis", "Myrospermum.frutescens", "Nectandra.cissiflora",
"Nectandra.lineata", "Nectandra.purpurea", "Ochroma.pyramidale",
"Ocotea.cernua", "Ocotea.oblonga", "Ocotea.puberula", "Ocotea.whitei",
"Oenocarpus.mapora", "Ormosia.amazonica", "Ormosia.coccinea",
"Ormosia.macrocalyx", "Pachira.quinata", "Pachira.sessilis",
"Perebea.xanthochyma", "Phoebe.cinnamomifolia", "Picramnia.latifolia",
"Piper.reticulatum", "Platymiscium.pinnatum", "Platypodium.elegans",
"Posoqueria.latifolia", "Poulsenia.armata", "Pourouma.bicolor",
"Pouteria.fossicola", "Pouteria.reticulata", "Pouteria.stipitata",
"Prioria.copaifera", "Protium.costaricense", "Protium.panamense",
"Protium.tenuifolium", "Pseudobombax.septenatum",
"Psidium.friedrichsthalianum", "Psychotria.grandis",
"Pterocarpus.rohrii", "Quararibea.asterolepis", "Quassia.amara",
"Randia.armata", "Sapium.broadleaf", "Sapium.glandulosum",
"Schizolobium.parahyba", "Senna.dariensis", "Simarouba.amara",
"Siparuna.guianensis", "Siparuna.pauciflora", "Sloanea.terniflora",
"Socratea.exorrhiza", "Solanum.hayesii", "Sorocea.affinis",
"Spachea.membranacea", "Spondias.mombin", "Spondias.radlkoferi",
"Sterculia.apetala", "Swartzia.simplex.var.grandiflora",
"Swartzia.simplex.var.ochnacea", "Symphonia.globulifera",
"Tabebuia.guayacan", "Tabebuia.rosea", "Tabernaemontana.arborea",
"Tachigali.versicolor", "Talisia.nervosa", "Talisia.princeps",
"Terminalia.amazonia", "Terminalia.oblonga",
"Tetragastris.panamensis", "Tetrathylacium.johansenii",
"Theobroma.cacao", "Thevetia.ahouai", "Tocoyena.pittieri",
"Trattinnickia.aspera", "Trema.micrantha", "Trichanthera.gigantea",
"Trichilia.pallida", "Trichilia.tuberculata",
"Trichospermum.galeottii", "Triplaris.cumingiana", "Trophis.caucana",
"Trophis.racemosa", "Turpinia.occidentalis", "Unonopsis.pittieri",
"Virola.multiflora", "Virola.sebifera", "Virola.surinamensis",
"Vismia.baccifera", "Vochysia.ferruginea", "Xylopia.macrantha",
"Zanthoxylum.ekmanii", "Zanthoxylum.juniperinum",
"Zanthoxylum.panamense", "Zanthoxylum.setulosum", "Zuelania.guidonia")

    if (!exists("BCI"))
        data("BCI", package = "vegan")
    nm <- names(BCI)
    k <- names(BCI) != oldnames
    noquote(cbind("Old Name" = oldnames,
                  "Current Name" = names(BCI))[k,])
}
